### ISSUE TITLE
Feature request: Another tab or filter for local feed on mastodon

### ISSUE THREAD

**Issue by silicology1** [pkreissel/fedifeed#2]
### Pitch

Get the gps location or through manual location entry of the profile, and display all tweets by profile within 50-100km, or any range or location selection, also filter by following and location or hastag and location etc.

Privacy may be concern. But without taking the exact location one can take approximate location with 50km error. Local journalist (news) and activist will get the chance to communicate with local people.

### Motivation

Here is an article why we need local journalism. 

[Why is trust in media in decline and what can be done about it?](https://jonmunitz.substack.com/p/trust-me-dia)

**Comment by pkreissel** [comment]
I think this is a good idea, but it is better suited for full on Mastodon Clients like elk and so on. 

The best way to implement this in my opinion would be via hashtags or a dedicated server for the local community. 

Fedifeed is just a frontend for an algorithmic feed, so it cannot collect location data.

**Comment by silicology1** [comment]
Ok, Can't it be implementation on frontend, if we ask users to provide their manual location in their profile?
