### ISSUE TITLE
[Feature Request] PWA

### ISSUE THREAD

**Issue by pablo03v** [pkreissel/fedifeed#3]
I would love to install fedifeed on my device. Maybe as a progressive web app

**Comment by pkreissel** [comment]
As of May 16th I will archive this Repo to continue development here: https://github.com/pkreissel/foryoufeed 
The new project enables me to do everything in react without a backend server. It is hosted here: https://vercel.com/pkreissel/foryoufeed 
If you only need the algorithm without all the fuss for your own project you can use this package: https://github.com/pkreissel/fedialgo
