### ISSUE TITLE
Herokuapp Error 500

### ISSUE THREAD

**Issue by stevenjlm** [pkreissel/fedifeed#4]
Not sure if the app is still supposed to be up and running, but online after giving the app access to my Mastodon account, I just get a 500 Error on the page.

I can provide more details if the herokuapp demo is important; however, I am working on local setup right now.

**Comment by pkreissel** [comment]
I am currently working on a browser only-variant - so no Webserver needed then. Will be finished this week I hope. This will replace this repo.

**Comment by stevenjlm** [comment]
Ah ok I see. Is the browser-only variant just using client side code for feed ranking? Using javascript or something?

**Comment by pkreissel** [comment]
Yes. It will be entirely written in JavaScript (React)

**Comment by stevenjlm** [comment]
I'll keep an eye out for when you release that then. I like the current version, but I understand the value of doing everything client-end.

**Comment by pkreissel** [comment]
As of May 16th I will archive this Repo to continue development here: https://github.com/pkreissel/foryoufeed 
The new project enables me to do everything in react without a backend server. It is hosted here: https://vercel.com/pkreissel/foryoufeed 
If you only need the algorithm without all the fuss for your own project you can use this package: https://github.com/pkreissel/fedialgo
