### ISSUE TITLE
Suggestions/questions for improving Setup and Readme

### ISSUE THREAD

**Issue by stevenjlm** [pkreissel/fedifeed#5]
I have things working locally, but I encountered some minor difficulties I would like to share.
 # Readme
For filling out the FIELD_ENCRYPTION_KEY environment variable the Readme seems to suggest that this comes from running, `manage.py generate_encryption_key`
This was giving me an error, so I filled FIELD_ENCRYPTION_KEY with the result from running,
```
$ python
>> from cryptography.fernet import Fernet
>> Fernet.generate_key()
```
Then I ran `manage.py generate_encryption_key` and used that result to populate the SECRET_KEY environment variable.
Does this make sense, or am I doing something weird? If it makes sense, I can open a PR with a modified Readme with these instructions. If there was a different expected behavior could you explain what I was supposed to do?

# Database
I was getting a NAME missing error from django when running the server, then I was missing the ENGINE etc. So I modified the settings.py file on line 102 with the following:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'fedifeed',
        'HOST': env("DATABASE_URL"),
        'PORT': '5432',                    
        'USER': env("DB_USER"),
        'PASSWORD': env("DB_PASSWORD"),                             
    }
}
```
and changed the env variable accordingly.

Am I missing something? Or does this make sense to be added into a PR?

**Comment by pkreissel** [comment]
As of May 16th I will archive this Repo to continue development here: https://github.com/pkreissel/foryoufeed 
The new project enables me to do everything in react without a backend server. It is hosted here: https://vercel.com/pkreissel/foryoufeed 
If you only need the algorithm without all the fuss for your own project you can use this package: https://github.com/pkreissel/fedialgo
